# Generated by Django 2.1.4 on 2019-03-04 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(verbose_name='Une petite description')),
                ('two_words', models.CharField(max_length=40, verbose_name='Votre coloc en deux mots')),
                ('mean_age', models.IntegerField(null=True)),
                ('pets', models.CharField(max_length=40, verbose_name='Animaux présents dans la coloc')),
            ],
            options={
                'verbose_name': 'Colocation',
                'ordering': ['intro'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=20, verbose_name='Ville')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'ordering': ['age'],
            },
        ),
        migrations.AddField(
            model_name='colocation',
            name='createur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Profil'),
        ),
    ]
