# Generated by Django 2.1.4 on 2019-03-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(verbose_name='Une petite description')),
                ('two_words', models.CharField(max_length=40, verbose_name='Votre coloc en deux mots')),
                ('mean_age', models.IntegerField(null=True)),
                ('pets', models.CharField(max_length=40, verbose_name='Animaux présents dans la coloc')),
            ],
            options={
                'verbose_name': 'Colocation',
                'ordering': ['intro'],
            },
        ),
    ]
