# Generated by Django 2.1.4 on 2019-01-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('age', models.IntegerField()),
                ('animals', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Colocation',
                'ordering': ['nom'],
            },
        ),
    ]
