# Generated by Django 2.1.4 on 2019-01-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yvette', '0003_auto_20190124_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'ordering': ['age'], 'verbose_name': 'Profil'},
        ),
        migrations.RemoveField(
            model_name='profil',
            name='email',
        ),
    ]
