# Generated by Django 2.1.4 on 2019-01-27 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yvette', '0004_auto_20190127_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField()),
                ('two_words', models.CharField(max_length=40)),
                ('mean_age', models.IntegerField(null=True)),
                ('pets', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Colocation',
                'ordering': ['user'],
            },
        ),
        migrations.AlterField(
            model_name='profil',
            name='city',
            field=models.CharField(max_length=20, verbose_name='Ville'),
        ),
    ]
