# Generated by Django 2.1.4 on 2019-01-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yvette', '0005_auto_20190127_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colocation',
            options={'ordering': ['intro'], 'verbose_name': 'Colocation'},
        ),
        migrations.RenameField(
            model_name='colocation',
            old_name='user',
            new_name='profil',
        ),
        migrations.AlterField(
            model_name='colocation',
            name='intro',
            field=models.TextField(verbose_name='Une petite description'),
        ),
        migrations.AlterField(
            model_name='colocation',
            name='pets',
            field=models.CharField(max_length=40, verbose_name='Animaux présents dans la coloc'),
        ),
        migrations.AlterField(
            model_name='colocation',
            name='two_words',
            field=models.CharField(max_length=40, verbose_name='Votre coloc en deux mots'),
        ),
    ]
