# Generated by Django 2.1.4 on 2019-01-27 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yvette', '0006_auto_20190127_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colocation',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yvette.Profil'),
        ),
    ]
