# Generated by Django 2.1.4 on 2019-01-31 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yvette', '0007_auto_20190127_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colocation',
            old_name='profil',
            new_name='createur',
        ),
    ]
