# Generated by Django 2.1.4 on 2019-01-31 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yvette', '0010_auto_20190131_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colocation',
            name='createur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yvette.Profil'),
        ),
    ]
